import './globals.scss'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="de" className="bg-black text-white">
      <body className="flex flex-col min-h-screen">{children}</body>
    </html>
  )
}
